rsync -a ./data/adam_wbn/norm/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm/4.0_1
rsync -a ./data/adam_wbn/cnorm/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm/4.0_1
rsync -a ./data/adam_wbn/cnormu/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu/4.0_1
rsync -a ./data/adam_wbn/gcstdu/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu/4.0_1
rsync -a ./data/adam_wbn/norm_div4/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div4/4.0_1
rsync -a ./data/adam_wbn/cnorm_div4/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div4/4.0_1
rsync -a ./data/adam_wbn/cnormu_div4/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div4/4.0_1
rsync -a ./data/adam_wbn/gcstdu_div4/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div4/4.0_1
rsync -a ./data/adam_wbn/norm_div8/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div8/4.0_1
rsync -a ./data/adam_wbn/cnorm_div8/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div8/4.0_1
rsync -a ./data/adam_wbn/cnormu_div8/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div8/4.0_1
rsync -a ./data/adam_wbn/gcstdu_div8/4.0_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div8/4.0_1
rsync -a ./data/adam_wbn/norm/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm/4.4_1
rsync -a ./data/adam_wbn/cnorm/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm/4.4_1
rsync -a ./data/adam_wbn/cnormu/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu/4.4_1
rsync -a ./data/adam_wbn/gcstdu/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu/4.4_1
rsync -a ./data/adam_wbn/norm_div4/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div4/4.4_1
rsync -a ./data/adam_wbn/cnorm_div4/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div4/4.4_1
rsync -a ./data/adam_wbn/cnormu_div4/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div4/4.4_1
rsync -a ./data/adam_wbn/gcstdu_div4/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div4/4.4_1
rsync -a ./data/adam_wbn/norm_div8/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div8/4.4_1
rsync -a ./data/adam_wbn/cnorm_div8/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div8/4.4_1
rsync -a ./data/adam_wbn/cnormu_div8/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div8/4.4_1
rsync -a ./data/adam_wbn/gcstdu_div8/4.4_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div8/4.4_1
rsync -a ./data/adam_wbn/norm/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm/4.8_1
rsync -a ./data/adam_wbn/cnorm/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm/4.8_1
rsync -a ./data/adam_wbn/cnormu/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu/4.8_1
rsync -a ./data/adam_wbn/gcstdu/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu/4.8_1
rsync -a ./data/adam_wbn/norm_div4/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div4/4.8_1
rsync -a ./data/adam_wbn/cnorm_div4/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div4/4.8_1
rsync -a ./data/adam_wbn/cnormu_div4/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div4/4.8_1
rsync -a ./data/adam_wbn/gcstdu_div4/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div4/4.8_1
rsync -a ./data/adam_wbn/norm_div8/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div8/4.8_1
rsync -a ./data/adam_wbn/cnorm_div8/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div8/4.8_1
rsync -a ./data/adam_wbn/cnormu_div8/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div8/4.8_1
rsync -a ./data/adam_wbn/gcstdu_div8/4.8_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div8/4.8_1
rsync -a ./data/adam_wbn/norm/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm/5.2_1
rsync -a ./data/adam_wbn/cnorm/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm/5.2_1
rsync -a ./data/adam_wbn/cnormu/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu/5.2_1
rsync -a ./data/adam_wbn/gcstdu/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu/5.2_1
rsync -a ./data/adam_wbn/norm_div4/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div4/5.2_1
rsync -a ./data/adam_wbn/cnorm_div4/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div4/5.2_1
rsync -a ./data/adam_wbn/cnormu_div4/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div4/5.2_1
rsync -a ./data/adam_wbn/gcstdu_div4/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div4/5.2_1
rsync -a ./data/adam_wbn/norm_div8/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/norm_div8/5.2_1
rsync -a ./data/adam_wbn/cnorm_div8/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnorm_div8/5.2_1
rsync -a ./data/adam_wbn/cnormu_div8/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/cnormu_div8/5.2_1
rsync -a ./data/adam_wbn/gcstdu_div8/5.2_1/ hpc:/share/users/student/l/llemke/bachelorthesis/data/adam_wbn/gcstdu_div8/5.2_1
