python run/global_center_std_uncenter.py adam 0.5 1
python run/global_center_std_uncenter.py adam 0.6 1
python run/global_center_std_uncenter.py adam 0.7 1
python run/global_center_std_uncenter.py adam 0.8 1
python run/global_center_std_uncenter.py adam 0.9 1
python run/global_center_std_uncenter.py adam 1.0 1
python run/global_center_std_uncenter.py adam 1.1 1
python run/global_center_std_uncenter.py adam 1.2 1
python run/global_center_std_uncenter.py adam 1.3 1
python run/global_center_std_uncenter.py adam 1.4 1

python run/global_center_std_uncenter.py adam 0.5 10
python run/global_center_std_uncenter.py adam 0.6 10
python run/global_center_std_uncenter.py adam 0.7 10
python run/global_center_std_uncenter.py adam 0.8 10
python run/global_center_std_uncenter.py adam 0.9 10
python run/global_center_std_uncenter.py adam 1.0 10
python run/global_center_std_uncenter.py adam 1.1 10
python run/global_center_std_uncenter.py adam 1.2 10
python run/global_center_std_uncenter.py adam 1.3 10
python run/global_center_std_uncenter.py adam 1.4 10

python run/global_center_std_uncenter.py adam 0.5 100
python run/global_center_std_uncenter.py adam 0.6 100
python run/global_center_std_uncenter.py adam 0.7 100
python run/global_center_std_uncenter.py adam 0.8 100
python run/global_center_std_uncenter.py adam 0.9 100
python run/global_center_std_uncenter.py adam 1.0 100
python run/global_center_std_uncenter.py adam 1.1 100
python run/global_center_std_uncenter.py adam 1.2 100
python run/global_center_std_uncenter.py adam 1.3 100
python run/global_center_std_uncenter.py adam 1.4 100