python main.py ./exps_sgdm/wd/0.014/ --reset
python main.py ./exps_sgdm/wd/0.005/ --reset
python main.py ./exps_sgdm/wd/0.011/ --reset
python main.py ./exps_sgdm/wd/0.001/ --reset
python main.py ./exps_sgdm/wd/0.006/ --reset
python main.py ./exps_sgdm/wd/0.002/ --reset
python main.py ./exps_sgdm/wd/0.009/ --reset
python main.py ./exps_sgdm/wd/0.007/ --reset
python main.py ./exps_sgdm/wd/0.004/ --reset
python main.py ./exps_sgdm/wd/0.003/ --reset
python main.py ./exps_sgdm/wd/0.01/ --reset
python main.py ./exps_sgdm/wd/0.013/ --reset
python main.py ./exps_sgdm/wd/0.008/ --reset
python main.py ./exps_sgdm/wd/0.012/ --reset