python main.py ./exps_sgdm/gcstdu_div4/0.4_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.2_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.25_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.05_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.3_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.45_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.1_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.15_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.5_1/ --reset
python main.py ./exps_sgdm/gcstdu_div4/0.35_1/ --reset
python main.py ./exps_sgdm/wd_div4/0.014/ --reset
python main.py ./exps_sgdm/wd_div4/0.005/ --reset
python main.py ./exps_sgdm/wd_div4/0.011/ --reset
python main.py ./exps_sgdm/wd_div4/0.001/ --reset
python main.py ./exps_sgdm/wd_div4/0.006/ --reset
python main.py ./exps_sgdm/wd_div4/0.002/ --reset
python main.py ./exps_sgdm/wd_div4/0.009/ --reset
python main.py ./exps_sgdm/wd_div4/0.007/ --reset
python main.py ./exps_sgdm/wd_div4/0.004/ --reset
python main.py ./exps_sgdm/wd_div4/0.003/ --reset
python main.py ./exps_sgdm/wd_div4/0.01/ --reset
python main.py ./exps_sgdm/wd_div4/0.013/ --reset
python main.py ./exps_sgdm/wd_div4/0.008/ --reset
python main.py ./exps_sgdm/wd_div4/0.012/ --reset
python main.py ./exps_sgdm/norm_div4/0.4_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.2_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.25_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.05_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.3_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.45_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.1_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.15_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.5_1/ --reset
python main.py ./exps_sgdm/norm_div4/0.35_1/ --reset
python main.py ./exps_sgdm/standard_div4/0.025/ --reset
python main.py ./exps_sgdm/standard_div4/0.005/ --reset
python main.py ./exps_sgdm/standard_div4/0.011/ --reset
python main.py ./exps_sgdm/standard_div4/0.044/ --reset
python main.py ./exps_sgdm/standard_div4/0.006/ --reset
python main.py ./exps_sgdm/standard_div4/0.016/ --reset
python main.py ./exps_sgdm/standard_div4/0.099/ --reset
python main.py ./exps_sgdm/standard_div4/0.008/ --reset