python run/reverse_center_norm_uncenter.py adam 0.5 1
python run/reverse_center_norm_uncenter.py adam 0.6 1
python run/reverse_center_norm_uncenter.py adam 0.7 1
python run/reverse_center_norm_uncenter.py adam 0.8 1
python run/reverse_center_norm_uncenter.py adam 0.9 1
python run/reverse_center_norm_uncenter.py adam 1.0 1
python run/reverse_center_norm_uncenter.py adam 1.1 1
python run/reverse_center_norm_uncenter.py adam 1.2 1
python run/reverse_center_norm_uncenter.py adam 1.3 1
python run/reverse_center_norm_uncenter.py adam 1.4 1